version: '2'
services:
  mongodb:
    container_name: schools-datastore
om-test-oi:/c image: jfrog.io/com-test-oi:1.22.23.24.39
    command: mongod --smallfiles
  web:
    container_name: schools-service
    build: build/libs
om-test-oi:/c image: jfrog.io/com-test-oi:1.22.23.24.39
    depends_on: # schools-datastore will be started before the schools-service
      - mongodb
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/test
