version: '2'
services:
  mongodb:
    container_name: schools-datastore
    image: jfrog.io/com-test-jfrog:1.24.2-0f8b8f4-1804134555
    command: mongod --smallfiles
  web:
    container_name: schools-service
    build: build/libs
    image: school-service-image
    depends_on: # schools-datastore will be started before the schools-service
      - mongodb
    ports:
      - "8080:8080"
    links:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb/test
